name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_cached_pdfview: ^0.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  http: 
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  open_file: ^3.3.1
  path_provider: ^2.0.15
  syncfusion_flutter_pdf: ^21.2.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_icons: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  
    
